### ISSUE TITLE
Implementation Details?

### ISSUE THREAD

**Issue by tim5go** [ehalit/KLOOS#1]
Would you mind sharing the implementation details of your paper, so that other people can reproduce the result?

**Comment by ehalit** [comment]
Sorry for the inconvenience but I am currently recovering from COVID-19 and unable to reach my work at my office. Once I get my hands on my office computer, I will provide further details. Do not expect any code piece to get uploaded though, because we are legally prohibited to upload any code or dataset generated within our company for public usage. I will prepare an instructive document for recreating the algorithm.

**Comment by tim5go** [comment]
@ehalit 
Oh...I'm sorry to hear that, please take good care of yourself.

**Comment by ehalit** [comment]
@tim5go 
Added a new document for implementation details, let me know if it is enough for recreating the algorithm or it needs further clarification.

**Comment by tim5go** [comment]
@ehalit 
Yes, it is clear enough, thanks~
